#image:maven:latest
image: maven:3-jdk-8

stages:
     -build
variables:
     MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
     paths:
          - .m2/repository/
          - target/

maven-build-stage:
     stage: build
     tags:
          -docker
     script:
          -echo "Maven compile started"
          -"mvn compile"

